# Generated by Django 5.0.3 on 2024-04-10 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_customuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid Egyptian phone number', regex='^20(10|11|12|15)\\d{8}$')]),
        ),
    ]
